import { SessionResult } from "@/types/question";

const OPTION_LABELS = ["A", "B", "C", "D"];

export function generateResultsPDF(result: SessionResult) {
  const { subjectName, topicName, total, correct, timeTaken, questionResults } = result;
  const pct = total > 0 ? Math.round((correct / total) * 100) : 0;
  const minutes = Math.floor(timeTaken / 60);
  const seconds = timeTaken % 60;

  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Quiz Results - ${subjectName} - ${topicName}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', system-ui, sans-serif; padding: 40px; color: #1a1a2e; background: #fff; }
  .header { text-align: center; margin-bottom: 32px; padding-bottom: 24px; border-bottom: 2px solid #e0e0e0; }
  .header h1 { font-size: 24px; margin-bottom: 4px; }
  .header p { color: #666; font-size: 14px; }
  .stats { display: flex; justify-content: center; gap: 32px; margin-bottom: 32px; }
  .stat { text-align: center; padding: 16px 24px; border: 1px solid #e0e0e0; border-radius: 12px; }
  .stat-value { font-size: 28px; font-weight: 700; }
  .stat-label { font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #888; margin-top: 4px; }
  .score-good { color: #22c55e; }
  .score-mid { color: #f59e0b; }
  .score-low { color: #ef4444; }
  .questions { margin-top: 24px; }
  .question { padding: 16px; margin-bottom: 12px; border: 1px solid #e8e8e8; border-radius: 8px; border-left: 4px solid; page-break-inside: avoid; }
  .question.correct { border-left-color: #22c55e; background: #f0fdf4; }
  .question.wrong { border-left-color: #ef4444; background: #fef2f2; }
  .q-text { font-size: 14px; font-weight: 600; margin-bottom: 8px; }
  .q-answer { font-size: 12px; color: #555; }
  .q-answer span.correct-text { color: #22c55e; font-weight: 600; }
  .q-answer span.wrong-text { color: #ef4444; font-weight: 600; }
  .footer { margin-top: 32px; text-align: center; color: #aaa; font-size: 11px; border-top: 1px solid #e0e0e0; padding-top: 16px; }
</style>
</head>
<body>
<div class="header">
  <h1>📝 Quiz Results</h1>
  <p>${subjectName} › ${topicName}</p>
  <p style="margin-top:4px;font-size:12px;color:#999;">${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}</p>
</div>
<div class="stats">
  <div class="stat">
    <div class="stat-value ${pct >= 70 ? 'score-good' : pct >= 40 ? 'score-mid' : 'score-low'}">${pct}%</div>
    <div class="stat-label">Score</div>
  </div>
  <div class="stat">
    <div class="stat-value">${correct}/${total}</div>
    <div class="stat-label">Correct</div>
  </div>
  <div class="stat">
    <div class="stat-value">${minutes}m ${seconds}s</div>
    <div class="stat-label">Time</div>
  </div>
</div>
<div class="questions">
  <h2 style="font-size:16px;margin-bottom:16px;">Question Review</h2>
  ${questionResults.map((qr, i) => `
    <div class="question ${qr.correct ? 'correct' : 'wrong'}">
      <div class="q-text">${i + 1}. ${qr.question.question}</div>
      <div class="q-answer">
        Your answer: <span class="${qr.correct ? 'correct-text' : 'wrong-text'}">${qr.selectedIndex >= 0 ? `${OPTION_LABELS[qr.selectedIndex]}. ${qr.question.options[qr.selectedIndex]}` : 'Not answered'}</span>
      </div>
      ${!qr.correct ? `<div class="q-answer">Correct: <span class="correct-text">${OPTION_LABELS[qr.question.answerIndex]}. ${qr.question.options[qr.question.answerIndex]}</span></div>` : ''}
    </div>
  `).join('')}
</div>
<div class="footer">Generated by Quest Ace</div>
</body>
</html>`;

  const printWindow = window.open('', '_blank');
  if (!printWindow) return;
  printWindow.document.write(htmlContent);
  printWindow.document.close();
  printWindow.onload = () => {
    printWindow.print();
  };
}
